- name: install linux config
  hosts: localhost
  tasks:
      - name: mkdir -p $HOME/.vim
        file:
            path: ~/.vim/UltiSnips
            state: directory

      - name: mkdir -p $HOME/.vim
        file:
            path: ~/.vim/autoload/
            state: directory

      - name: copy UltiSnips
        copy:
            src: UltiSnips/
            dest: ~/.vim/UltiSnips/
            force: yes

      - name: copyc plug.vim
        copy:
            src: plug.vim
            dest: ~/.vim/autoload/plug.vim
            force: yes

      - name: copy vimrc
        copy:
            src: vimrc
            dest: ~/.vim/vimrc
            force: yes

      - name: create .conf
        file:
            path: $HOME/.config/i3
            state: directory

      - name: config bash
        lineinfile:
            path: ~/.bashrc
            line: source {{playbook_dir}}/bashrc
            insertafter: .*VISUAL.*

      - name: config tmux
        copy:
            src: tmux.config
            dest: ~/.tmux.conf
            force: yes

      - name: config tools
        lineinfile:
            path: ~/.bashrc
            line: export PATH=$PATH:{{playbook_dir}}/tools
            insertafter: source.*bashrc

      - name: config bashmarks.sh
        lineinfile:
            path: ~/.bashrc
            line: source {{playbook_dir}}/bashmarks.sh
            insertafter: export.*tools

      - name: config i3
        copy:
            src: i3.config
            dest: ~/.config/i3/config
            force: yes
      - name: create cargo home
        file:
            path: ~/.cargo/bin
            state: directory

      - name: config cargo 
        copy:
            src: cargo.config
            dest: ~/.cargo/config
            force: yes
      - name: mkdir ~/.config/alacritty
        file:
            path: ~/.config/alacritty
            state: directory
      - name: copy alacritty.yml
        copy:
            src: alacritty.yml
            dest: ~/.config/alacritty/alacritty.yml
