#!/usr/bin/env perl
use Getopt::Long;

sub usage($);

GetOptions("all" => \(my $all),
           "h|help"     => \(my $help));
sub usage($) {
    my $code = shift;
    my $msg = <<EOF;
nodes [options]  display k8s nodes.
    -h
    --help       Print help message

    --all        Print hostname and ip address, if not set then print ip only.
EOF
    print($msg);
    exit($code);
}

if($help) {
    usage(0);
}

sub nodes (){
    my @lines = `kubectl get nodes |grep -v NAME`;
    my @hosts;
    foreach my $line (@lines) {
       chomp($line);
       next unless(length($line));
       my @flags = split(/\s+/,$line);
       push @hosts, $flags[0];
    }
    return \@hosts;
}

sub nslookup ($) {
    my $host = shift;
    my $line = `nslookup $host | grep Address | grep -v \\#`;
    my @flags = split(/\s+/,$line);
    return $flags[1];
}


my $hosts = nodes();
foreach my $node (@$hosts) {
    if($all) {
        printf "%-40s\t%s\n", $node, nslookup($node);
    } else {
        printf "%s\n", nslookup($node);
    }
}
